apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: bmFncA==

---

apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: nagp
  # Db user
  POSTGRES_USER: nagp
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: postgresdb-service
  #PGDATA: /var/lib/postgresql/data/pgdata