apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  # Name the persistent chain
  name: postgresdb-pv
  # Labels for identifying PV
  labels:
    type: local
    app: postgresdb
spec:
  capacity:
    # PV Storage capacity
    storage: 1Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteOnce
  # Specify the path to persistent the volumes  
  hostPath:
    path: /mnt/disks
  #persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
# define a resource for volume chain
kind: PersistentVolumeClaim
metadata:
  # Name the volume chain
  name: db-pv-claim
spec:
  storageClassName: ""
  accessModes:
    # Allow ReadWrite to multiple pods
    - ReadWriteOnce
  # PVC requesting resources
  resources:
    requests:
      # the PVC storage
      storage: 1Gi

---

# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: postgresdb
spec:
  strategy:
    type: Recreate
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: postgresdb
    spec:
      containers:
        # The container name to execute pods
        - name: postgresdb
          # pull postgresimage from docker hub
          image: postgres
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: db-secret-credentials
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgresql/data
            #- mountPath: /opt
              name: db-data
      # Volumes attached to the pod
      volumes:
        - name: db-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: db-pv-claim

---

apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: postgresdb-service
  labels:
    app: postgresdb
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # Pod to route service traffic  
  selector:
    app: postgresdb